apiVersion: v2
appVersion: 9.5.0.02
dependencies:
- alias: waserver
  condition: waserver.enableServer
  name: wa-server-prod
  repository: ""
  version: 1.1.0
- alias: waconsole
  condition: waconsole.enableConsole
  name: wa-console-prod
  repository: ""
  version: 1.1.0
- alias: waagent
  condition: waagent.enableAgent
  name: wa-dyn-agent-prod
  repository: ""
  version: 1.1.0
description: Helm chart for configuring IBM Workload Automation.
keywords:
- Commercial
- amd64
- Workload Scheduler
- Workload Automation
- Automation
- DevOps
- ICP
kubeVersion: '>=1.14.0 || >=1.14.0-0'
maintainers:
- name: IBM Workload Automation
name: workload-automation-prod
version: 1.1.0
