####################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2020. All rights reserved.
#
# * Trademark of HCL Technologies Limited
####################################################################
global:
  language: en
  license: accept
  serviceAccountName: wauser
  enablePrometheus: true
  customLabels:
    - name: "environment"
      value: "prod"
waagent: 
  enableAgent: true
  runAsUser: 999
  fsGroupId: 999
  supplementalGroupId:
  agent:
    containerDebug: false
    dynamic:
      certSecretName: ca-key-pair
      useSaaSConfig: false
      saasConfig:
        engine: sijr27wamxo-355.wa.ibmserviceengage.com
        subscriptionID: 
        controllerHostname: wastagdal05gov.wa.ibmserviceengage.com
        userID: 
        password: 
      pools: null
      server:
        mdmhostname: "wa-server-route-my-wa-prj.apps.mcm-demo-env.pnp-soln.ml"
        port: "443"
      useCustomizedCert: false
    livenessProbe:
      initialDelaySeconds: 60
    name: gke-wa-agent
    tz: null
  image:
    pullPolicy: Always
    repository: cp.icr.io/cp/ibm-workload-automation-agent-dynamic
    tag: 9.5.0.02.20200727
  persistence:
    dataPVC:
      name: data
      selector:
        label: ""
        value: ""
      size: 2Gi
      storageClassName: ""
    enabled: true
    useDynamicProvisioning: true
  replicaCount: 1
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 200Mi
waconsole:
  enableConsole: false
  runAsUser: 999
  fsGroupId: 999
  supplementalGroupId:
  console:
    certSecretName: waconsole-cert-secret
    containerDebug: false
    engineHostName:
    enginePort:
    db:
      adminUser: db2inst1
      hostname: dbhost
      name: DWC
      port: 50000
      sslConnection: false
      tsName: null
      tsPath: null
      tsTempName: null
      tssbspace: null
      type: DB2
      usepartitioning: true
      user: db2inst1
    routes:
      enabled: true
    ingress:
      hostname: 
      secretName: wa-console-ingress-secret
    exposeServiceType: Ingress
    exposeServiceAnnotation: {}
      #cert-manager.io/issuer: wa-ca-issuer
      #service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
      #service.beta.kubernetes.io/aws-load-balancer-type: "clb"
      #service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      #service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    libConfigName: null
    livenessProbe:
      initialDelaySeconds: 100
    pwdSecretName: wa-pwd-secret
    useCustomizedCert: false
  image:
    pullPolicy: Always
    repository: cp.icr.io/cp/ibm-workload-automation-console
    tag: 9.5.0.02.20200727
  persistence:
    dataPVC:
      name: data
      selector:
        label: ""
        value: ""
      size: 5Gi
      storageClassName: ""
    enabled: true
    useDynamicProvisioning: true
  replicaCount: 1
  resources:
    limits:
      cpu: 4
      memory: 16Gi
    requests:
      cpu: 1
      memory: 4Gi
waserver:  
  enableServer: false
  runAsUser: 999
  fsGroupId: 999
  supplementalGroupId:
  image:
    pullPolicy: Always
    repository: cp.icr.io/cp/ibm-workload-automation-server
    tag: 9.5.0.02.20200727
  persistence:
    dataPVC:
      name: data
      selector:
        label: ""
        value: ""
      size: 10Gi
      storageClassName: ""
    enabled: true
    useDynamicProvisioning: true
  replicaCount: 1
  resources:
    limits:
      cpu: 4
      memory: 16Gi
    requests:
      cpu: 1
      memory: 4Gi
  server:
    agentName: WA_SAGT
    certSecretName: waserver-cert-secret
    company: my-company
    containerDebug: false
    createPlan: true
    dateFormat: MM/DD/YYYY
    db:
      adminUser: db2inst1
      hostname: dbhost
      name: TWS
      port: 50000
      sslConnection: false
      tsLogName: null
      tsLogPath: null
      tsName: null
      tsPath: null
      tsPlanName: null
      tsPlanPath: null
      tsTempName: null
      tssbspace: null
      type: DB2
      usepartitioning: true
      user: db2inst1
    routes:
      enabled: true
      hostname:
    ingress:
      hostname: 
      secretName: wa-server-ingress-secret
    exposeServiceType: Ingress
    exposeServiceAnnotation: {}
      #service.beta.kubernetes.io/aws-load-balancer-type: nlb
      #service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    libConfigName: null
    licenseServerId: null
    licenseServerUrl: null
    readinessProbe:
      initialDelaySeconds: 600
    livenessProbe:
      initialDelaySeconds: 600
    pwdSecretName: wa-pwd-secret
    startOfDay: "0700"
    timezone: null
    tz: null
    useCustomizedCert: false
